projects/TravelExperts/TravelExpertsMVC/Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TravelExpertsData;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TravelExpertsMVC.Controllers
{
   
    public class BookingController : Controller
    {
        private readonly TravelExpertsContext _context;

        public BookingController(TravelExpertsContext context)
        {
            _context = context;
        }
        public int CustomerId { get; private set; }

        // GET: BookingController

        // Main static booking page to display all packages and details
        public ActionResult Booking()
        {
            return View();
        }


        // Create a MyBookings page only displays information for a customer that is logged in. (Coded by: Muhammad, with help from Ali)
        [Authorize]
        public async Task<IActionResult> MyBooking()
        {

            if (User.Identity.Name != null)
            {
                decimal totalbookingCost = 0;
                int customerId = CustomerManager.FindCustomer(User.Identity.Name, _context).CustomerId;
                List<Booking> custBooking = _context.Bookings
                    .Include(b => b.BookingDetails) // Include BookingDetails
                    .Include(b => b.Package)
                    .Where(c => c.CustomerId == customerId)
                    .ToList();


                // Calculate the total cost of all the packages present in the customers profile. (Coded by: Muhammad, with help from Ali)
                custBooking.ForEach(c =>
                {
                    if (c.PackageId != null)
                    {
                        totalbookingCost += calCost(c);
                  
                    }
                });

                ViewBag.TotalCost = totalbookingCost.ToString("c");
                return View(custBooking);
            }
            else
            {
                return View("Index", "Home");
            }


        }

        // Total cost formula. (Coded by: Muhammad, with help by Ali)
        private decimal calCost(Booking booking)
        {
            return (booking.Package.PkgBasePrice * Convert.ToDecimal(booking.TravelerCount));

        }


        // Delete each booking from the customers profile. (Coded by: Muhammad, with help from Ali)
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.BookingDetails)
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings.FindAsync(id);
            _context.Bookings.Remove(booking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MyBooking));
        }
    }
}

projects/TravelExperts/TravelExpertsMVC/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace TravelExpertsMVC.Controllers
{
    public class ContactController : Controller
    {
        //Static view for the contact page (can later be employee information taken from the sql database) (Coded by: Muhammad, with help from Ali) 
        public IActionResult Contact()
        {
            return View();
        }
    }
}

projects/TravelExperts/TravelExpertsMVC/Controllers/PackagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using TravelExpertsData;

namespace TravelExpertsMVC.Controllers
{
    [Authorize]
    public class PackagesController : Controller
    {
        private readonly TravelExpertsContext _context;

        public PackagesController(TravelExpertsContext context)
        {
            _context = context;
        }

        // Get and display all packages available (Coded by: Ali, with help from Muhammad)
        public ActionResult Packages()
        {
            List<Package> packages = PackageManager.GetAllPackages();
            return View(packages);
        }

        //Create funchtionably to add packages to the logged in customer database. (Coded by: Muhammad, with help from Ali)
        [HttpPost]
        public async Task<IActionResult> BookPackage(int packageId, string bookingId)
        {
            if (User.Identity.Name == null)
            {
                // If the user is not logged in, redirect to the login page
                return RedirectToAction("Login", "Account");
            }

            // Find the customer ID of the logged-in user
            int customerId = CustomerManager.FindCustomer(User.Identity.Name, _context).CustomerId;

            // Get the traveler count from the form data
            int travelerCount = int.Parse(Request.Form["travelerCount"]);

            // Create a new booking and set its customer ID, package ID, booking number, and traveler count
            Booking booking = new Booking();
            booking.CustomerId = customerId;
            booking.PackageId = packageId;
            booking.BookingDate = DateTime.Today;
            booking.TravelerCount = travelerCount;

            // Add the booking to the context and save changes to the database
            _context.Bookings.Add(booking);
            await _context.SaveChangesAsync();

            // Redirect to the MyBooking action method to show the updated booking list
            return RedirectToAction("MyBooking", "Booking");
        }

        // GET: PackagesController/Details/5



    }
}

projects/TravelExperts/TravelExpertsMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelExpertsMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TravelExpertsMVC.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/lib/images/LogoLG.png" style="height: 65px; width: 50px;" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Booking">Packages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Packages" asp-action="Packages">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="MyBooking">My Booking</a>
                        </li>  
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contact">Contact Us</a>
                        </li>                       
                    </ul>                                 
                                
            </div>
                <partial name="_LoginPartial" />
                <partial name="_RegisterPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

</body>
<footer class="border-top footer text-muted pd-5/>
    <div class="container">
        &copy; 2023 - TravelExpertsMVC <br />
        Follow us:
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
        </svg>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</footer>
</html>

projects/TravelExperts/TravelExpertsMVC/Views/Shared/_RegisterPartial.cshtml
<ul class="navbar-nav ml-auto">

    @if (User.Identity.IsAuthenticated)

    {

        <li class="nav-item">

            <p class="nav-link text-dark">

                Welcome @User.Identity.Name

            </p>

        </li>

        <li class="nav-item">

            <form class="form-inline" asp-controller="Account" asp-action="Logout"
                     asp-route-returnUrl=@Url.Action("Index", "Home")>

                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>

            </form>

        </li>

    }

    else

    {

        <li class="nav-item">

            <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">

                Register

            </a>

        </li>

    }

</ul>